### ISSUE TITLE
"Uncaught Type Error" in java script console logs on WebRTC Trouble shooter page on device 

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#684] opened 2015-11-10 19:06 UTC
Repro steps:
1. Navigate to https://test.webrtc.org/ 
2. Click on 'Start' 
3. Observe that tests passed successfully for Camera, Throughput and tests passed with warning sign for Microphone, Network, Connectivity ( working as expected)
4. Notice that java script console logs show this error "Uncaught TypeError: Cannot read property 'reportError' of undefined"

Expected result:
All tests on WebRTC troubleshooter page should pass without any errors in java script console logs.

Actual result:
Tests are passing but java script console logs show "Uncaught Type Error"

**Comment by tednakamura** [comment] 2015-11-10 21:30
cvranjani@ - can you copy/paste the console content? It's difficult to debug those kind of errors with the exact text. :)

**Comment by cvranjani** [comment] 2015-11-10 21:59
Java script console logs:

"This appears to be Chrome
analytics.js:30 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
(index):15555 chrome: {"audio":true,"video":true}
(index):15555 chrome: {"audio":{"optional":[{"echoCancellation":false},{"sourceId":"default"}]}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":320,"maxWidth":320,"minHeight":240,"maxHeight":240}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":640,"maxWidth":640,"minHeight":480,"maxHeight":480}}}
(index):20890 Uncaught TypeError: Cannot read property 'reportError' of undefined(anonymous function) @ (index):20890(anonymous function) @ (index):20928CamResolutionsTest.onCallEnded_ @ (index):20927getStats_ @ (index):20140gotStats_ @ (index):20158
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":720,"maxHeight":720}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":160,"maxWidth":160,"minHeight":120,"maxHeight":120}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":160,"maxWidth":160,"minHeight":120,"maxHeight":120}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":320,"maxWidth":320,"minHeight":180,"maxHeight":180}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":320,"maxWidth":320,"minHeight":240,"maxHeight":240}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":640,"maxWidth":640,"minHeight":360,"maxHeight":360}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":640,"maxWidth":640,"minHeight":480,"maxHeight":480}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":768,"maxWidth":768,"minHeight":576,"maxHeight":576}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1024,"maxWidth":1024,"minHeight":576,"maxHeight":576}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":720,"maxHeight":720}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":768,"maxHeight":768}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":800,"maxHeight":800}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1920,"maxWidth":1920,"minHeight":1080,"maxHeight":1080}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1920,"maxWidth":1920,"minHeight":1200,"maxHeight":1200}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":3840,"maxWidth":3840,"minHeight":2160,"maxHeight":2160}}}
(index):15555 chrome: {"audio":false,"video":{"mandatory":{"minWidth":4096,"maxWidth":4096,"minHeight":2160,"maxHeight":2160}}}
(index):15555 chrome: {"audio":false,"video":{"optional":[{"minWidth":1280},{"minHeight":720},{"sourceId":"09e10be906ba6ac6942a873c59dbf291ba183d69e603c86ff06fbc5513133ac5"}]}} "

**Comment by cvranjani** [comment] 2015-11-10 23:36
Observed the same issue on device big.

**Comment by KaptenJansson** [comment] 2015-11-11 08:52
You could also upload a report from the page which will contain all the info, click on the bug icon up to the right and add a description then click upload report. Copy the URL here.

Also this is wrong repo, should be filed in https://github.com/webrtc/testrtc/.

WRT to the error you are seeing, I cannot reproduce this due to testing on more powerful machines however I do see the issue, I'm not binding to the proper scope for the videoTrack events (muted, unmute and ended) which are usually not triggered during the tests on powerful machines but are very often triggered on slower machines.

Fixed in https://github.com/webrtc/testrtc/pull/147.

**Closed as completed** 2015-11-11 09:02 UTC

**Comment by KaptenJansson** [comment] 2015-11-11 09:19
And it's now pushed, please try it out.
