### ISSUE TITLE
Video source selection not honored in munge-sdp/ samples page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#695] opened 2015-11-20 20:24 UTC
Steps to reproduce:
1. Check the Audio and Video settings in the browser chrome://settings/content
2. Make sure you have atleast 2 cameras and 2 mics setup in the machine
3. Go to https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/ samples page
4. Select a video source from the dropdown (NOT the ones in browser settings), then click Get media
5. Once the peerconnection is set up, the offer is created (and set), Create and Set Answer
6. Confirm the audio and video source that is seen/heard

Expected results:
The Video source selection from the dropdown should be honored

Actual results:
The Video source is the one from the browser settings 

Test environment: 
Chrome 48.0.2564.11
Test machine - Mac 10.10.5
2 cameras in test - FaceTime HD and Logitech external. 
3 mics in test - Default, Built-in (headset) and Logitech webcam mic

Before the start of the test, I had FaceTime HD camera and Built-in (headset) mic selected in chrome://settings/content, and this is what I see/hear AFTER the peerconnection is set, inspite of selecting Logitech Camera and Mic from the dropdown in the page

(Also happens in Ubuntu 14.04 and Windows 7)

**Comment by KaptenJansson** [comment] 2016-02-03 10:16
Confirmed that it always selects the default camera.
Log

```
This appears to be Chrome
main.js:91 unknown {"deviceId":"default","kind":"audiooutput","label":"Default","groupId":"2004946474"}
main.js:91 unknown {"deviceId":"50d6078c5697b991241586c9c006a591bbf12816b564700f1e102350e563e4d7","kind":"audiooutput","label":"Built-in Audio Analog Stereo","groupId":"3275026054"}
common.js:8 1.993: Selected audio source: undefined
common.js:8 1.993: Selected video source: undefined
common.js:8 1.994: Requested local stream
adapter.js:32 spec:   {"audio":{"optional":[{"sourceId":"undefined"}]},"video":{"optional":[{"sourceId":"undefined"}]}}
adapter.js:32 chrome: {"audio":{"optional":[{"sourceId":"undefined"}]},"video":{"optional":[{"sourceId":"undefined"}]}}
common.js:8 2.005: Received local stream
```

Most likely due to trying to grab videoSource.id rather than videoSource.deviceId here https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/munge-sdp/js/main.js#L76.

Should update to use enumerateDevices + deviceId property.

**Comment by ErikHellman** [comment] 2018-07-18 06:15
Closing this as it has been fixed already.

**Closed as completed by ErikHellman** 2018-07-18 06:15 UTC
Labels: bug
