### ISSUE TITLE
Error processing ICE candidate

### ISSUE THREAD

**Issue by Dmole** [webrtc/samples#1202] opened 2019-07-15 14:59 UTC
# Please read first!

- [yes] I have provided steps to reproduce
- [yes] I have provided browser name and version
- [yes] I have provided a link to the sample here or a modified version thereof

## Browser affected
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
	released 2019-07-09
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/75.0.3770.90 Chrome/75.0.3770.90 Safari/537.36"
	released 2019-06-04

## Description
Messages:  
addIceCandidate: OperationError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
	gitHash:    c8e4f11ecccef40e92f577ede737e81d76b319ed
	branch:     master
	time:       Tue Feb 26 14:22:13 2019 +0100

## Steps to reproduce
Visit https://appr.tc/ with the latest firefox release and the latest chrome release and try to have a audio video call.

## Expected results
audio and video in both directions.

## Actual results
audio only from firefox to chrome.

I suspect a change in Firefox caused this as we only noticed it break our webrtc tool recently,
so I filed a bug there to https://bugzilla.mozilla.org/show_bug.cgi?id=1566095

**Comment by nils-ohlmeier** [comment] 2019-07-25 17:26
So the error in Chrome is caused by Firefox implementing the latest spec on handling ICE candidates ihttps://bugzilla.mozilla.org/show_bug.cgi?id=1318167. AFAIK this should be fixed now in the latest Chromium according to https://bugs.chromium.org/p/chromium/issues/detail?id=978582

**Comment by Dmole** [comment] 2019-07-25 17:36
Yes firefox enabled TX of that feature to soon. There should be a way to work around it in JavaScript until the next chromium release.

**Comment by nils-ohlmeier** [comment] 2019-07-25 19:55
Yes you could for example drop the empty string `""` candidates from Fierfox and not call `addIceCandidate()` with them.

**Comment by 1591582901** [comment] 2020-05-14 02:44
But I use the latest version of Google browser, which also has this problem

**Comment by 1591582901** [comment] 2020-05-14 02:45
But I use the latest version of Google browser, which also has this problem

**Comment by fippo** [comment] 2022-04-07 15:38
no longer relevant (and apprtc is gone)

**Closed as completed by fippo** 2022-04-07 15:38 UTC
