### ISSUE TITLE
no picture on Android

### ISSUE THREAD

**Issue by horald** [webrtc/samples#1067] opened 2018-07-13 15:58 UTC
## Browser affected

Chrome Version 65.0.3325.109 for Android

Apache/2.4.18 (Ubuntu) on Linux Computer
Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:14:58 UTC 2018 i686 

## Description
the webcam with Chrome on my Android phone stays black. The camera authorization for Chrome is switched on! On my Linux computer I'm asked for a camera permission in Firefox, then I can see pictures. Why can't I do that on my cell phone? Thanks for helpful tips.

## Steps to reproduce
apache on Linux computer
Run Demo https://ip-linux-computer/samples/src/content/getusermedia/canvas/ with Android-Chrome on cell phone

## Expected results
show camera picture

## Actual results
black box

**Comment by ErikHellman** [comment] 2018-07-16 13:40
I'm testing this with version 67.0.3396.87 on Android O and it works fine. Can you test again with the latest version of Chrome and see if the problem remains?

**Comment by ErikHellman** [comment] 2018-07-23 10:59
Ping @horald. Any update on this?

**Comment by ErikHellman** [comment] 2018-08-29 08:17
Closing this as I can't reproduce it and not getting any additional information. Please file a new issue if it is still a problem.

**Closed as completed by ErikHellman** 2018-08-29 08:17 UTC
