### ISSUE TITLE
The duration of the video downloaded form the record demo is null

### ISSUE THREAD

**Issue by jumpymariox** [webrtc/samples#1168] opened 2018-12-19 18:38 UTC
# Please read first!

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Chrome Version 70.0.3538.110 (Official Build) (64-bit)

## Description

The duration of the video downloaded by the record demo is null

## Steps to reproduce

Open the demo in `samples/src/content/getusermedia/record/index.html`, and record and download the video.
Use the ffmpeg to check the info of video.

## Expected results

The video downloaded has its normal duration time.

## Actual results

The video downloaded's duration time is null.
![image](https://user-images.githubusercontent.com/18607553/50240518-feed0200-03ff-11e9-88ae-d680b195da0c.png)

**Comment by acbuitrago** [comment] 2019-03-07 22:46
Hi! This issue is caused by a bug in [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=642012) and not something specific to this project. 

Basically, in Chrome the duration of the recorded media isn't added to the headers of the final file. Sadly, this bug is currently marked as `WontFix` by the Chromium team. However, there are a couple of workarounds:
- Using ffmpeg to fix the headers: `ffmpeg -i old.webm output.webm`
- On the frontside, you could use the workaround on [this answer](https://stackoverflow.com/questions/38443084/how-can-i-add-predefined-length-to-audio-recorded-from-mediarecorder-in-chrome/39971175#39971175) or use the package [ts-ebml ](https://www.npmjs.com/package/ts-ebml)

**Comment by fippo** [comment] 2022-03-20 08:29
closing per the comment above.

**Closed as completed by fippo** 2022-03-20 08:29 UTC
