### ISSUE TITLE
connection a session- how to init/connect for the first time?

### ISSUE THREAD

**Issue by Jleinwand** [webrtc/samples#848] opened 2016-12-01 11:14 UTC
**Browsers and versions affected**
Chrome

**Description**
Initializing/connecting to a session fails.
Uncaught syntax error: invalid or unexpected token.

**Steps to reproduce**
Using OpenTalk tutorial recommendation, open learning-opentalk-web; web folder; run local server via Python in Terminal; launch local server in Chrome (the webcam starts); open developer console in Chrome; copy Opentok API info to session initializer js code.

**Expected results**
see chat window.

**Actual results**
see only video of self.
<img width="1275" alt="screen shot 2016-12-01 at 12 40 09 am" src="https://cloud.githubusercontent.com/assets/24293182/20791937/766da29e-b763-11e6-9b6e-2b871683d93b.png">

**Comment by ggarber** [comment] 2016-12-01 13:39
This is not the best place for OpenTok questions.   You should try https://support.tokbox.com/hc/en-us or even StackOverflow.

The problem is probably the missing quotes around the apiKey and sessionId as @fippo pointed you in the mailing list.

I suggest you closing this issue because this is the place for discussions and issues only for the generic WebRTC sample applications.

Gustavo Garcia (TokBox employee)

**Comment by KaptenJansson** [comment] 2016-12-02 07:41
Thanks @ggarber.

**Closed as completed by KaptenJansson** 2016-12-02 07:41 UTC
