### ISSUE TITLE
Transmit text samples doesn't work on mobile safari nor mobile chrome

### ISSUE THREAD

**Issue by jonnyijapan** [webrtc/samples#1187] opened 2019-03-28 00:39 UTC
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Mobile Chrome iOS as of 20190328
Mobile Safari iOS 12.2

## Description
https://webrtc.github.io/samples/src/content/datachannel/basic/ Doesn't work

## Steps to reproduce
Open the page, tap start, but you can't enter any text in any of the text views.

## Expected results
I expect to be able to input text in the text views.

## Actual results
Keyboard never opens. Can't input text.

**Comment by nkev** [comment] 2019-05-19 09:18
Same issue (cannot enter text) on Webkit OSX. Works in Firefox but not Chrome or Safari on my Macbook. Disappointing.

**Comment by fippo** [comment] 2022-04-08 07:30
duplicate of #1123

**Closed as completed by fippo** 2022-04-08 07:30 UTC
