### ISSUE TITLE
Webrtc rear camera not working in IOS 11

### ISSUE THREAD

**Issue by myselfgaurav** [webrtc/samples#1023] opened 2018-03-10 09:23 UTC
Below is my code that work fine in android and ios 11 with front camera while when i use rear camera it gives error

**below works**

    video: { width: 400, height: 200, facingMode: "user"  }

**Below not works**

    video: { width: 400, height: 200, facingMode: "environment"  }

**Complete code**

**

    var constraints = window.constraints = {
      audio: false,
      video: { width: 400, height: 200, facingMode: "environment"  }
    };
    function handleSuccess(stream) {
      var videoTracks = stream.getVideoTracks();
      console.log('Got stream with constraints:', constraints);
      console.log('Using video device: ' + videoTracks[0].label);
      stream.oninactive = function() {
        console.log('Stream inactive');
      };
      window.stream = stream; // make variable available to browser console
      video.srcObject = stream;
    }
    function handleError(error) {
      if (error.name === 'ConstraintNotSatisfiedError') {
        errorMsg('The resolution ' + constraints.video.width.exact + 'x' +
            constraints.video.width.exact + ' px is not supported by your device.');
      } else if (error.name === 'PermissionDeniedError') {
        errorMsg('Permissions have not been granted to use your camera and ' +
          'microphone, you need to allow the page access to your devices in ' +
          'order for the demo to work.');
      }
      errorMsg('getUserMedia error: ' + error.name, error);
    }
    function errorMsg(msg, error) {
      errorElement.innerHTML += '<p>' + msg + '</p>';
      if (typeof error !== 'undefined') {
        console.error(error);
      }
    }
    navigator.mediaDevices.getUserMedia(constraints).
        then(handleSuccess).catch(handleError);

**

**Comment by tetreault** [comment] 2018-06-05 00:02
I wonder how this is working for you. I'm on iOS 11.4 on iphone X and no webrtc demos are working for me that use the phone's cam for video :(

**Comment by myselfgaurav** [comment] 2018-06-05 03:03
that works fine on iOS

**Comment by tetreault** [comment] 2018-06-05 13:20
not for me @myselfgaurav - i've even taken your complete JS and placed it in my file, nothing happens in my mobile safari.

**Comment by tetreault** [comment] 2018-06-05 14:35
you're right @myselfgaurav - was a mistake on my end :)

**Comment by ErikHellman** [comment] 2018-07-18 05:44
I'm closing this since it's not a bug in one of the samples. If you still have problems with your WebRTC code, see https://webrtc.org/bugs/ for reporting this on the different browsers.

**Closed as completed by ErikHellman** 2018-07-18 05:44 UTC

**Comment by bflorat** [comment] 2018-10-10 08:29
@tetreault  : how did you fixed that ? I have the same problem, thanks.

**Comment by tetreault** [comment] 2018-10-10 13:09
my issue was odd @bflorat. in my case i had done an iOS update, which for some reason disabled javascript... super odd, but obviously no code demos would work if JS was disabled.

**Comment by bflorat** [comment] 2018-10-10 13:30
Thanks for your response, I finally made it work. I had several issues : 
* The website MUST be in HTTPS otherwise, none media stream is opened (and no error). Works with HTTP under Android.
* The width and height of the video constraints MUST be omitted, otherwise, nothing is shown (works under Android)
* We must have a ios version with a fix for  https://bugs.webkit.org/show_bug.cgi?id=187756  (was my case in ios 12.0.1 but I didn't figured out the ios version where this fix was incorporated)

My final video constraints to make the rear camera work as expected : 
audio: false,
facingMode: "environment"

**Comment by tetreault** [comment] 2018-10-10 15:53
oh another thing you want to keep in mind @bflorat - from my experience apple ONLY implemented WebRTC in mobile safari. I had a web app that used WebRTC for front facing camera and can confirm WebRTC was not working properly in iOS Chrome, iOS FF, standalone PWA mode (its a webview), nor does it work in the webviews in social apps like facebook, instagram.

**Comment by nadelicious** [comment] 2018-12-11 07:58
it should be `video: { deviceId: { exact: 'cameraFront/Back deviceId'  }` . You can get the front and back deviceId through `navigator.mediaDevices.enumerateDevices()` [promise] ;
