### ISSUE TITLE
Data Channel (Generate and transfer data sample): JS Error "Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'"

### ISSUE THREAD

**Issue by JaspalK** [webrtc/samples#894] opened 2017-04-28 14:54 UTC
**Browsers and versions affected**
Chrome 60.0.3080.5 / Dev

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Uncheck "Ordered mode"
4. Click on "Generate and Send data" for the default size 128 MB

**Expected results**
Step 3:  No JS errors
           'Send & Receive' progress bars are fully filled with blue

**Actual results**
Actual:
Step 3:  JS error "Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'"
         (see attached screenshot)

**Other information**
The complete JS log can be found at:

https://docs.google.com/document/d/1NaoX8tV65a2VHqc4pvKD7gwGurOANvLpaNgVroOwDa4/edit

The bug is not reproduceable every time.  Infact if you reload the page after "Uncaught DOMException the JS error, you don't get the JS error

I have also noticed this bug before on MacOS 10.12.4   I will update this bug if I see it on Linux Ubuntu 14.04

![data-channel_exception](https://cloud.githubusercontent.com/assets/22443950/25534092/124b1c84-2c33-11e7-878c-359abb53eaef.PNG)

**Comment by fippo** [comment] 2017-04-28 15:55
hrm. This looks like the data channel is closed and then used to send more data.
The receiver does close on receivedSize === bytesToSend (which is somewhat unfortunate...)

If you can reproduce can you check the values of sendProgress.value and sendProgress.max?

**Comment by JaspalK** [comment] 2017-05-02 07:48
Sure @fippo I can provide those values when I next can reproduce the bug

**Comment by JaspalK** [comment] 2017-06-01 11:48
@fippo:  I got the fault again:

sendProgress.value  = 133628000
sendProgress.max = 134218000

**Comment by fippo** [comment] 2017-06-01 12:05
that looks pretty far off, I expected it to be at most one chunk too much.

I think this is an issue with the strategy/protocol of the sample rather than Chrome though.

**Comment by rantonysamy** [comment] 2017-11-14 11:04
Any fix versions for this issue ?

**Comment by KaptenJansson** [comment] 2017-11-16 13:45
Not planned sorry. As long as it's not happening every time it will have low prio.

**Comment by ErikHellman** [comment] 2018-07-23 10:41
I've seen this happen sometimes and I agree with @fippo that it probably has more to do with the protocol in this sample. 

I would suggest a redesign of this sample where the first message contains the total size of the data and the receiver can use that to determine the progress.

I'll try to have a PR for that ready ASAP.

**Comment by ErikHellman** [comment] 2018-08-29 11:39
I've refactored this sample quite a bit now and this shouldn't happen anymore. I'm closing this, but feel free to reopen if it comes up again.

**Closed as completed by ErikHellman** 2018-08-29 11:39 UTC
Labels: bug
