### ISSUE TITLE
No audio for audio only page and RTCDTMFSender

### ISSUE THREAD

**Issue by Adwarakanathan** [webrtc/samples#624] opened 2015-08-27 15:50 UTC
Steps:
1. Go to https://webrtc.github.io/samples/src/content/peerconnection/audio/ and click call. 
2. Talk through microphone and listen to it.

BUG: No audio is heard

1. Go to https://webrtc.github.io/samples/src/content/peerconnection/dtmf/ and click 'Call' And then 'Send tones'. 
2. Verify you hear the tone in your speaker/headphone

Bug: No audio is heard

**Comment by tednakamura** [comment] 2015-09-01 22:49
I can also reproduce this with today's Canary (47.0.2498.0), and as far back as Chrome 43.0.2357.81 (I didn't check any further back). Possible hint - I can get the DTMF tones to playout if I have a call running in https://webrtc.github.io/samples/src/content/peerconnection/pc1/ in another tab. Sample steps:

1) Open https://webrtc.github.io/samples/ in one tab
2) Click "Basic peer connection demo" (aka pc1) so that it opens in another tab in the same window as 1) 
3) Click "Use RTCDTMFSender" (aka dtmf) so that it opens in another tab in the same window as 1) and 2) 
4) In pc1, establish the call by pressing Start and Call
5) In dtmf, press the Call button
6) In dtmf, send some tones

With that flow, on desktop, dtmf tones play out. If pc1 and dtmf are not in tabs associated with the same window, the dtmf tones do not play out. And just as strange, if I just open pc1 and dtmf manually in adjacent tabs, then dtmf tones do _not_ play out. Since this repros with Chrome 43, I don't think this problem is due to a recent Chrome bug, but I have a hard time understanding why some sort of "shared state" allows dtmf tones to sometimes play out.

**Comment by KaptenJansson** [comment] 2015-09-02 11:05
Fixed in #626.

It was caused by only doing .src shimming on Video elements and not on audio elements.

You could see that if you looked at the src attribute of the audio element that it was just an empty string rather than a blob.

**Closed by KaptenJansson** 2015-09-02 11:05 UTC
