### ISSUE TITLE
Remote video not shown in /pr-answer/ page in M49

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#709] opened 2015-12-09 22:16 UTC
Steps to repro:
1. Open https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/ in M49 Canary
2. Press "Call" button 
3. Press "Accept" button

Expected result:
Video should be seen in the remote end (on the right side)

Actual result:
No video seen in the remote end

Notes:
1. This is a regression from M48. Works fine in M48 Beta 48.0.2564.41 (and earlier versions), but issue is seen in M49 Canary 49.0.2585.0 & 49.0.2586.0 
2. No JS error in console 

Console logs attached 
[pr-answer console logs.txt](https://github.com/webrtc/samples/files/57404/pr-answer.console.logs.txt)

Referencing https://github.com/webrtc/samples/issues/178

**Comment by srnarayanan** [comment] 2015-12-09 22:18
Referencing https://github.com/webrtc/samples/issues/178

**Comment by srnarayanan** [comment] 2015-12-10 21:03
Chromium bug for reference - https://code.google.com/p/chromium/issues/detail?id=568734

**Comment by alvestrand** [comment] 2016-11-12 14:07
Works for me in Version 54.0.2840.100 (64-bit) on Ubuntu. Closing unitl someone reproduces.

**Closed as completed by alvestrand** 2016-11-12 14:07 UTC
Labels: bug-in-chrome
