### ISSUE TITLE
Selecting an empty file after selecting a non-empty file crashed file transfer page

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#705] opened 2015-12-02 22:42 UTC
Repro steps:
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click the "Choose File" button
4. Select a file of any size (non-empty file)
5. Observe that file is transferred and link to download  "Click to download $filename" is available
6. Now select an empty file(0 bytes) 
7. Observe that page is crashed with error "Aw, Snap! Something went wrong while displaying this webpage"

Please see following logs for additional information
https://drive.google.com/a/google.com/file/d/0B84heIonLi5IVnZnUVRISXZSUUpqU1JDdnVxOWVxUEpaNlZR/view?usp=sharing

Note:
1. This issue is not happening consistently ( seen 80% of the times)
2. Observed this issue currently on chromebox Guado

**Comment by samdutton** [comment] 2015-12-03 12:07
Can reproduce on 46.0.2490.86 and 49.0.2580.0 on Mac.

**Comment by samdutton** [comment] 2015-12-03 12:24
Inserted a breakpoint at the call to `closeDataChannels()` on line 80 and got the crash after resuming, so assume this is going wrong in `closeDataChannels()`. 

With breakpoint in `closeDataChannels()` can't yet get crash :(. Will keep trying.

Timing issue of some type, I guess...

**Comment by KaptenJansson** [comment] 2018-03-08 14:13
Closing due to age.

**Closed as completed by KaptenJansson** 2018-03-08 14:13 UTC
Labels: bug, bug-in-chrome
