### ISSUE TITLE
not able to initiate webcam for capture of new image 

### ISSUE THREAD

**Issue by 123AP** [webrtc/samples#1044] opened 2018-05-04 05:18 UTC
""looking for complete javascript code to access multiple camera drivers"""".

I am trying to use multiple cameras on web application . List of camera drivers should come in the drop down. I should be able to choose required camera driver from the drop down. Based on my selection, i will capture the photo. Whenver i change the drop down option, the corresponding camera driver should open."

CURRENTLY USING RTCMulticonnection for accessing multiple devices *

**Comment by ErikHellman** [comment] 2018-07-18 05:25
Closing this since it's not a bug in one of the existing samples. 

See https://webrtc.org/bugs/ for reporting bugs on WebRTC.

See https://webrtc.github.io/samples/src/content/devices/input-output/ for a sample on selecting media devices.

**Closed as completed by ErikHellman** 2018-07-18 05:25 UTC
