### ISSUE TITLE
Media Stream Record example includes un-used MediaSource code that when used can throw errors

### ISSUE THREAD

**Issue by guest271314** [webrtc/samples#1256] opened 2020-01-25 20:59 UTC
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [X ] I have provided steps to reproduce
- [X ] I have provided browser name and version
- [X ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

- Firefox 72.0.1
- Nightly 74.0a1
- Chromium 81.0.4033.2

## Description

Firefox, Nightly errors
```
video/webm;codecs=vp9 is not Supported
ReferenceError: errorMsgElement is not defined
```

## Steps to reproduce

See https://stackoverflow.com/questions/59860029/how-to-use-mediarecorder-as-mediasource which references https://webrtc.github.io/samples/src/content/getusermedia/record/ as the source of the code.

Run the linked jsfiddle https://jsfiddle.net/43rm7258/1/, which will result in errors at Firefox, Nightly, and Chromium. 

## Expected results

The OP of the SO question is using code from the repository expecting to stream output of `MediaRecorder` as input to `MediaSource`. 

## Actual results

`MediaRecorder` and `MediaSource` codecs are not guaranteed to be an exact match using the code in that example, where the `MediaSource` code is actually used. Several checks are used for `MediaRecorder.isTypeSupported()` output, none for `MediaSource.isTypeSupported()`, nor to check if the output of both codec support checks for the respective API is `true` for the same value.

At the current source code in this repository `getUserMedia()` is executed with contraints including `audio`. However, the codec set for `SourceBuffer` does not include `"opus"`. That omission will result in an error if a user actually tries to use that code with the recorded `Blob`s or delayed streaming, which OP of the SO question is evidently attempting to achieve.

One solution for the OP would be to just hardcode the code `"video/webm;codecs=vp8"` due to the fact that Firefox does not support VP9 encoding for all of the API's that Chromium might.

Alternatively, check for common MIME type before running any `MediaRecorder` or `MediaSource` code, e.g., 
```

const mimeCodecs = ["video/webm;codecs=vp9,opus", "video/webm;codecs=vp8,opus"];
const mimeCodec = mimeCodecs.find(codec => MediaRecorder.isTypeSupported(codec) && MediaSource.isTypeSupported(codec));
//
  const superBuffer = new Blob(recordedBlobs, {type: mimeCodec});
// 
  const blob = new Blob(recordedBlobs, {type: mimeCodec});
//
function handleSourceOpen(event) {
  console.log('MediaSource opened');
  if (MediaSource.isTypeSupported(mimeCodec)) {
    sourceBuffer = mediaSource.addSourceBuffer(mimeCodec);
    console.log('Source buffer: ', sourceBuffer);
  } else {
    console.log(mimeCodec + ' supported: ' + MediaSource.isTypeSupported(mimeCodec));
  }
}
//
let options = {mimeType: mimeCodec};
  if (!MediaRecorder.isTypeSupported(options.mimeType)) {
    console.error(`${options.mimeType} is not Supported`);
    errorMsgElement.innerHTML = `${options.mimeType} is not Supported`;
    options = {mimeType: mimeCodecs.find(codec => codec !== options.mimeType)};
    if (!MediaRecorder.isTypeSupported(options.mimeType)) {
      console.error(`${options.mimeType} is not Supported`);
      errorMsgElement.innerHTML = `${options.mimeType} is not Supported`;
      options = {mimeType: 'video/webm'};
      if (!MediaRecorder.isTypeSupported(options.mimeType)) {
        console.error(`${options.mimeType} is not Supported`);
        errorMsgElement.innerHTML = `${options.mimeType} is not Supported`;
        options = {mimeType: ''};
      }
    }
```

Or, `MediaSource` code can be removed entirely from the example in this repository due to that example does not appear to use `MediaSource`. 

Is the `MediaSource` code intended to be used in the "Media Stream Record" example?

**Comment by baptx** [comment] 2020-03-29 10:51
I can confirm that the sample https://webrtc.github.io/samples/src/content/getusermedia/record/ is not working on latest Firefox stable version (74.0 Linux 64-bit version from Ubuntu package). In the console, I can see that `video/webm;codecs=vp9 is not Supported` and there is an error when I start recording: `NotSupportedError: MediaRecorder.start: An audio track cannot be recorded: video/webm;codecs=vp8 indicates an unsupported codec`.
The problem was fixed by either removing the options parameter of `MediaRecorder` or using the codec `video/webm;codecs=vp8,opus` instead of `video/webm;codecs=vp8`.
Isn't it better to not use the options parameter so the web browser can choose the best codec? When I tried to record a WebRTC livestream on a website with `MediaRecorder` and `captureStream()` / `mozCaptureStream()`, I saw with VLC video player that Firefox used VP8 by default and Chromium used H264 by default (however VP8 is used by default for the sample link in both Firefox and Chromium).
Any idea when Firefox will support VP9 completely?

**Closed as completed** 2020-05-18 10:57 UTC
