### ISSUE TITLE
Uncaught TypeError thrown in peerconnection/munge-sdp page 

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#738] opened 2016-01-15 20:02 UTC
Precondition: Have the machine connected to a slower Wifi connection (maybe "..Guest")

Steps to reproduce:
1. Open the peerconnection/munge-sdp/ page https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/
2. Click on "Get Media" and wait for the video to appear in Local
3. Click on "Create peer connection", "Create Offer", "Set Offer", and then "Create answer" 
4. Confirm that we see data in the Answer SDP box
5. Now, Click "Set Answer" and before you see the video in Remote, quickly click "Hang up"

Actual results:
Uncaught TypeError: Cannot read property 'close' of undefined is thrown

Notes:
1. I did see this error on a faster non-guest wifi connection too, but we need to Hang up pretty quickly. 
On a slower connection, the video takes a while to appear, so it's easy to reproduce
2. This cannot be reproduced on a wired connection (afaict)

Screenshot:

<img width="960" alt="munge-sdp" src="https://cloud.githubusercontent.com/assets/14947786/12363825/c3fbbd74-bb7f-11e5-98f8-131c32f870ed.png">

**Comment by fippo** [comment] 2016-01-15 20:19
:+1: -- actually easier to repro:
- get media
- create peerconnection
- create offer
- hang up

The problem is that the receiveChannel is created in ondatachannel. Which happens after the connection is established which on a slow wifi takes more time to happen. Should be fixed in #739

**Closed as completed** 2016-01-18 08:40 UTC
