### ISSUE TITLE
Progress bar not shown when an empty file is chosen for file transfer after transferring a non-empty file

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#697] opened 2015-11-23 18:21 UTC
Repro steps:
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click the "Choose File" button
4. Select a file of any size (non-empty)
5. Observe file transfer through "Send progress" and "Receive progress" bars.
   and also the "Click to download $filename" link after file transfer
6. Now click on "Choose File" button and select an empty file(file with 0 bytes )
7. Observe that "Send progress" and "Receive progress" bars remain unchanged and "Click to download $filename" link still shows the file transferred in step 3.

Expected results:
Selecting an empty file for file transfer should result in message "File is empty, please select a non-empty file"

Actual results:
Selecting an empty file after transferring a non-empty file:
a) is not showing message "File is empty, please select a non-empty file" 
b) "Send progress" and "Receive progress" bars remain unchanged
c) "Click to download $filename" link still shows the file that was transferred previously

 Java script console logs:

"This appears to be Chrome
common.js:8 8.429: Created local peer connection object localConnection
common.js:8 8.438: Created send data channel
common.js:8 8.449: Created remote peer connection object remoteConnection
common.js:8 8.489: Offer from localConnection 
v=0
o=- 280315329748569179 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:7tJcFSyVu42opTzp
a=ice-pwd:74RSJUNY5kCEqCU69qpvryY1
a=fingerprint:sha-256 9D:D5:D6:6E:08:F4:5D:9A:3E:C8:C6:FA:53:8C:2D:65:CF:C7:AB:5B:DC:BF:0B:8B:7F:E8:FE:EF:E3:3C:F6:97
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 8.522: Answer from remoteConnection 
v=0
o=- 7567231516906172698 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:iC6ACve/lH9Z2MMc
a=ice-pwd:oOwmf65xsHewK6mMblw2VSMm
a=fingerprint:sha-256 9D:D5:D6:6E:08:F4:5D:9A:3E:C8:C6:FA:53:8C:2D:65:CF:C7:AB:5B:DC:BF:0B:8B:7F:E8:FE:EF:E3:3C:F6:97
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 8.528: local ice callback
common.js:8 8.533: Local ICE candidate: 
candidate:4273728266 1 udp 2113937151 192.168.1.125 39407 typ host generation 0
common.js:8 8.537: AddIceCandidate success.
common.js:8 8.540: remote ice callback
common.js:8 8.549: Remote ICE candidate: 
candidate:4273728266 1 udp 2113937151 192.168.1.125 38300 typ host generation 0
common.js:8 8.561: AddIceCandidate success.
common.js:8 8.564: remote ice callback
common.js:8 8.567: local ice callback
common.js:8 9.579: Send channel state is: open
common.js:8 9.584: file is arabic.txt 2018 text/plain Fri Nov 20 2015 10:14:41 GMT-0800 (PST)
common.js:8 9.595: Receive Channel Callback
common.js:8 9.597: Receive channel state is: open
common.js:8 9.608: Closing data channels
common.js:8 9.614: Closed data channel with label: sendDataChannel
common.js:8 9.617: Closed data channel with label: sendDataChannel
common.js:8 9.620: Closed peer connections
common.js:8 9.633: Send channel state is: closed
common.js:8 9.636: Receive channel state is: closed
common.js:8 19.132: Created local peer connection object localConnection
common.js:8 19.134: Created send data channel
common.js:8 19.138: Created remote peer connection object remoteConnection
common.js:8 19.147: Offer from localConnection 
v=0
o=- 1796182068225626586 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:AVR6YxKAyj6tPLBz
a=ice-pwd:vyyUbFVKsTrDX8viDfZ/xVzF
a=fingerprint:sha-256 9D:D5:D6:6E:08:F4:5D:9A:3E:C8:C6:FA:53:8C:2D:65:CF:C7:AB:5B:DC:BF:0B:8B:7F:E8:FE:EF:E3:3C:F6:97
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 19.167: Answer from remoteConnection 
v=0
o=- 5051238314494168326 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:Szqps36stXwUBP31
a=ice-pwd:hPxxNlqM7rSQUWFHZXdX+jzu
a=fingerprint:sha-256 9D:D5:D6:6E:08:F4:5D:9A:3E:C8:C6:FA:53:8C:2D:65:CF:C7:AB:5B:DC:BF:0B:8B:7F:E8:FE:EF:E3:3C:F6:97
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 19.176: local ice callback
common.js:8 19.187: Local ICE candidate: 
candidate:4273728266 1 udp 2113937151 192.168.1.125 52437 typ host generation 0
common.js:8 19.203: AddIceCandidate success.
common.js:8 19.216: remote ice callback
common.js:8 19.219: Remote ICE candidate: 
candidate:4273728266 1 udp 2113937151 192.168.1.125 59136 typ host generation 0
common.js:8 19.222: remote ice callback
common.js:8 19.225: AddIceCandidate success.
common.js:8 19.228: local ice callback
common.js:8 20.243: Send channel state is: open
common.js:8 20.245: file is x 0 Wed Nov 11 2015 15:34:28 GMT-0800 (PST)
common.js:8 20.245: Closing data channels
common.js:8 20.252: Closed data channel with label: sendDataChannel
common.js:8 20.252: Closed data channel with label: sendDataChannel
common.js:8 20.261: Closed peer connections
common.js:8 20.267: Send channel state is: closed "

**Comment by samdutton** [comment] 2015-11-24 12:33
Thanks @cvranjani!

Just confirmed this (selecting an empty file after selecting a non-empty file).

Turns out `<span id="status"></span>` is in `<a id="received"></a>` and gets clobbered once the value of `downloadDiv` is set. 

I'll do a PR to sort this out — variable naming needs tidying, too.

**Comment by KaptenJansson** [comment] 2018-03-08 14:14
Closing due to age.

**Comment by samdutton** [comment] 2018-03-15 16:16
@KaptenJansson This seems to have been fixed.

Working as intended (for me at least!)

**Closed as completed** 2018-05-29 14:00 UTC
Labels: bug
