### ISSUE TITLE
Multiple-relay link is not showing the video in the remote side

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#680] opened 2015-11-09 21:58 UTC
Steps:
1. Go to the https://webrtc.github.io/samples/src/content/peerconnection/multiple-relay in the device spring
2. Click on 'start' and should see the video in the local window
3. click on 'insert relay' and should see the remote video in the remote window
4. click on 'insert relay' again and again

Expected result:
Everytime the relay is pressed the count should be increased under the local video showing the increase in the number of elements in chain and also the video in the remote window should be seen

Actual result:
The count increase in proportionate to the number of insert relay clicks, but the video in the remote window is not seen

There are no errors seen in the js console.  There was a similar bug which i filed in chromium in mar 2015 which is 463225, but that was duplicated to another bug and was verified later.  But, it is happening again.

**Comment by samdutton** [comment] 2015-11-09 23:05
I can't reproduce this in 46.0.2490.80 (64-bit) or Version 48.0.2559.0 canary (64-bit) on Mac.

(Silly question maybe, but are you pressing the Call button?)

What Chrome version/OS are you on?

**Comment by fippo** [comment] 2015-11-09 23:10
the peerconnection updates and stats data that can be downloaded from chrome://webrtc-internals/ would be helpful too.

**Comment by cvranjani** [comment] 2015-11-10 00:06
Observed this issue on device samus and jaq with version:
Chrome: 48.0.2558.0
OS: 7625.0.0 dev

Pressed 'Call' button  before trying to 'Insert relay' :)

**Comment by KaptenJansson** [comment] 2015-11-10 10:23
I think all of these bugs are a symptom of the CEOD and Turn server being down yesterday. Please retest today.

**Comment by selavazhagan** [comment] 2015-11-10 20:03
Tried with the build 48.0.2558.0/7628.0.0 dev in Celes and Jerry, still not seeing the video in the remote window.  But, not seeing any errors in the js console logs too.

**Comment by tednakamura** [comment] 2015-11-10 21:36
Are you only seeing these remote video rendering failures with ChromeOS devices? If so, please track that in the chromium bug tracker.

**Comment by selavazhagan** [comment] 2015-11-10 22:04
Filed the chromium bug 554235

**Comment by tednakamura** [comment] 2015-11-11 14:42
Closing issue since we're now tracking this in [chromium bug 554235](http://crbug.com/554235).

**Closed as completed by tednakamura** 2015-11-11 14:42 UTC
