### ISSUE TITLE
Crashing after Stablish Connection between peers

### ISSUE THREAD

**Issue by Animeshdfoe** [webrtc/samples#1024] opened 2018-03-12 05:03 UTC
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

## Actual results

After Connetion establish then after 5 to 10 min app getting unhandled exception in webrtc libaray.
How to resolve this issuse please help me....
Thanks

**Comment by ErikHellman** [comment] 2018-07-18 05:41
Closing this since it's not a bug in one of the samples. Please refer to webrtc.org for reporting bugs on webrtc in the affected browser.

**Closed as completed by ErikHellman** 2018-07-18 05:41 UTC
