### ISSUE TITLE
'Uncaught Type Error' shown in javascript console after stopping web audio input call

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#673] opened 2015-10-29 19:48 UTC
Repro steps:
1. Navigate to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input
2. Open the javascript console (alt+cmd+j or ctr+shift+j) 
3.  Click 'Start' 
4. After few seconds, click on 'Stop' 
5. Observe 'Uncaught TypeError: localStream.stop is not a function' in Javascript console
6. Click 'Stop' and now observe 'Uncaught TypeError: Cannot read property 'disconnect' of null' in the javascript console

Note: Javascript console shows error even though Web audio input call is stopped after clicking on 'Stop'

Expected result:
No errors in javascript console 

Actual result:
'Uncaught Type Error' shown in javascript console after stopping web audio input call

**Comment by cvranjani** [comment] 2015-10-29 19:50
Javascript logs:

This appears to be Chrome
adapter.js:32 chrome: {"audio":true,"video":false}
main.js:66 gotStream({audio:true, video:false})
main.js:72 Created local peer connection object pc1
main.js:75 Created remote peer connection object pc2
main.js:111 Offer from pc1 
v=0
o=- 5597314813118689675 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS c6510bf6-0d4d-46cc-9db9-071aacfb94e4
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:RgqXhXC/WkEkbmes
a=ice-pwd:+vFITMTNq+C3hjJGg7Q2JmZp
a=fingerprint:sha-256 B2:79:B0:16:41:D3:B9:84:D9:23:31:85:C7:B8:22:B1:13:E2:97:A8:AE:5F:1A:A0:40:60:0F:A2:BE:DC:E1:59
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:4103285427 cname:cabD4oS/t1TblvQ/
a=ssrc:4103285427 msid:c6510bf6-0d4d-46cc-9db9-071aacfb94e4 266ea8ef-1d10-4b46-a6c1-9b2cc4ac1022
a=ssrc:4103285427 mslabel:c6510bf6-0d4d-46cc-9db9-071aacfb94e4
a=ssrc:4103285427 label:266ea8ef-1d10-4b46-a6c1-9b2cc4ac1022

main.js:117 Offer from pc1 
v=0
o=- 5597314813118689675 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS c6510bf6-0d4d-46cc-9db9-071aacfb94e4
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:RgqXhXC/WkEkbmes
a=ice-pwd:+vFITMTNq+C3hjJGg7Q2JmZp
a=fingerprint:sha-256 B2:79:B0:16:41:D3:B9:84:D9:23:31:85:C7:B8:22:B1:13:E2:97:A8:AE:5F:1A:A0:40:60:0F:A2:BE:DC:E1:59
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=maxptime:60
a=ssrc:4103285427 cname:cabD4oS/t1TblvQ/
a=ssrc:4103285427 msid:c6510bf6-0d4d-46cc-9db9-071aacfb94e4 266ea8ef-1d10-4b46-a6c1-9b2cc4ac1022
a=ssrc:4103285427 mslabel:c6510bf6-0d4d-46cc-9db9-071aacfb94e4
a=ssrc:4103285427 label:266ea8ef-1d10-4b46-a6c1-9b2cc4ac1022

main.js:124 Answer from pc2 
v=0
o=- 4944815438013334610 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8 13
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:UAZXS72vddyHKsOt
a=ice-pwd:ZOxr01fevd6+l1ZtPXYxBrgl
a=fingerprint:sha-256 B2:79:B0:16:41:D3:B9:84:D9:23:31:85:C7:B8:22:B1:13:E2:97:A8:AE:5F:1A:A0:40:60:0F:A2:BE:DC:E1:59
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=maxptime:60

main.js:136 Local ICE candidate: 
candidate:1775372849 1 udp 2122260223 192.168.1.137 60558 typ host generation 0
main.js:136 Local ICE candidate: 
candidate:1775372849 2 udp 2122260222 192.168.1.137 43700 typ host generation 0
main.js:144 Remote ICE candidate: 
 candidate:1775372849 1 udp 2122260223 192.168.1.137 43494 typ host generation 0
main.js:59 Uncaught TypeError: localStream.stop is not a functionstop @ main.js:59
webaudioextended.js:44 Uncaught TypeError: Cannot read property 'disconnect' of nullWebAudioExtended.stop @ webaudioextended.js:44stop @ main.js:51

**Comment by fippo** [comment] 2015-10-29 21:26
Thanks, should be fixed in PR #674.
Likely caused by the deprecation of MediaStream.stop -- are you using Chrome Canary/Beta?

@KaptenJansson might be worth sending a deprecation reminder email with many :fire: :boom: emojis :-)

**Comment by cvranjani** [comment] 2015-10-29 21:29
I am using Chrome OS  Beta ( 7520.24.0)

**Closed as completed** 2015-10-30 10:42 UTC

**Comment by samdutton** [comment] 2015-10-30 10:47
BTW the deprecation warning on Chrome 46 suggests using `MediaStream.active` instead of `MediaStream.stop()`, but of course `active` is read only, so also referring to `MediaStreamTrack.stop()` would be better. I'll see if someone can fix.

**Comment by fippo** [comment] 2015-10-30 14:49
@samdutton this came up before, I think it is already fixed in Canary. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/FcURcb1ZS90/Z64a-JiHBgAJ

**Comment by samdutton** [comment] 2015-10-30 15:33
Ah — well spotted @fippo.
