### ISSUE TITLE
Uncaught TypeError thrown in peerconnection/audio page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#733] opened 2016-01-11 21:03 UTC
Steps to reproduce:
1. Open https://webrtc.github.io/samples/src/content/peerconnection/audio/ in M49 Canary or M47 Stable
2. Let the codec be "Opus"
3. Click on "Call" and "Hang Up" buttons one after the other repeatedly (leaving no time between the 2 clicks)
4. Observe the JS console logs

Expected results:
No JS console errors seen

Actual results:
After around 20-30 clicks on "Call" and "Hang Up" repeatedly, the JS error "Uncaught TypeError: Cannot read property 'addIceCandidate' of null" is seen after "Ending call"
Attached screenshot.
Saw this issue in both Win and Mac

![uncaught typeerror](https://cloud.githubusercontent.com/assets/14947786/12246513/b5dc10c8-b863-11e5-86e8-9bbeb6922977.png)

**Comment by fippo** [comment] 2016-01-12 18:37
that's an odd one. I managed to reproduce with http://hancke.name/webrtc/fastclose.html -- creates and closes peerconnections until it runs into an error. Deploy it to https and execute call() in the console once.

I suspect this is a chrome issue where it still fires onicecandidate after stop has been called (hangup() disposes the peerconnections after calling close)
@KaptenJansson wdyt? There are a number of workarounds here, ranging from modifying addIceCandidate to check for existence to onicecandidate checking the pc it belongs to still exists to waiting for the iceconnection or signalingstate moving to closed.

@srnarayanan good catch and... how can you click that fast?! :-)

**Comment by KaptenJansson** [comment] 2016-02-03 09:59
I think it makes sense to just add a check to the event and see if the PC still exists.

**Comment by KaptenJansson** [comment] 2018-03-08 14:13
Closing due to age and no critical impact.

**Closed as completed by KaptenJansson** 2018-03-08 14:13 UTC
Labels: bug
