### ISSUE TITLE
Screen blacks out when min-width sent as 1920px

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#955] opened 2017-11-17 12:53 UTC
**Browsers and versions affected**
Chromebooks

**Description**
If min width sent as Overconstrainted (1920px), there should be OverconstraintedError, but Instead the screen blacks out with Video dimensions - 2x2px error.

**Steps to reproduce**
get a Chrome book - Go to https://webrtc.github.io/samples/src/content/peerconnection/constraints/
Setup the Min width to the maximum (1920px) and rest of all to 0
Click on Get Media 
Click on Connect

**Expected results**
OverconstraintedError should be displayed 

**Actual results**
Its connected to the peer with a blacked out screen.  (refer the screenshot)
![overconstraintederror](https://user-images.githubusercontent.com/32895099/32948166-a15bb784-cb9e-11e7-99b5-6553fa6d6995.png)

**Comment by KaptenJansson** [comment] 2017-11-17 13:05
This is up to the device to respond properly, if it does the overconstrained error will be shown. In this case getUserMedia succeeds but the camera fails to deliver video. getUserMedia is a just request for media, not a guarantee hence the underlying devices can fail and not produce anything.

What we could add here though is a message that the trackEnded event has fired (that's when you see black frames and 2x2 resolution). You can check that this is the case by looking at the ended property of the MediaStream returned from getUserMedia.

**Comment by rantonysamy** [comment] 2017-11-17 13:20
Okey that would be great !!

**Comment by KaptenJansson** [comment] 2018-02-02 08:33
Feel free to create a PR with this if you think it's important.

**Comment by getify** [comment] 2018-06-09 06:34
@rantonysamy Are you still experiencing this bug? If so, can you see what `chrome://media-internals` reports? Specifically, do you happen to have `WebPluginVirtualCamera` installed?

The reason I ask is, I'm having this issue (the 2x2 black video), and I'm trying to track down why it's happening. You're the only other one I've found who has seen the problem.

More info in that thread (on webrtc/adapter) linked immediately above.

**Comment by ErikHellman** [comment] 2018-07-18 12:36
I'm testing this now and I'm getting an OverconstraintedError as expected in Chrome. Can we close this?

**Comment by ErikHellman** [comment] 2018-08-29 08:24
I'm closing this as I can't reproduce the error. Please file a new issue in case this is still a problem.

**Closed as completed by ErikHellman** 2018-08-29 08:24 UTC
Labels: enhancement
