### ISSUE TITLE
Seeing '404 not found'  in the getsuermedia/resolution page

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#538] opened 2015-06-30 19:04 UTC
Steps:

1. Use the link http://webrtc.github.io/samples/src/content/getusermedia/resolution/
2. Click on the 'QVGA, VGA, HD and FullHD' options individually
3. Check for any errors or warnings in the console by clicking ctrl+shift+J

Expected result: 
There should be no errors seen

Actual result:
There is no problem seen in the functionality of the page or the tabs selected.  The video is fine but the error message is seen with the status code '404 not found' for the requested url: http://webrtc.github.io/samples/src/content/getusermedia/resolution/null

The screenshot is attached.
![screenshot 2015-06-30 at 12 02 40 pm](https://cloud.githubusercontent.com/assets/9001606/8439332/34141dc4-1f20-11e5-80d5-324ab86cba72.png)

**Comment by KaptenJansson** [comment] 2015-07-01 05:56
Dupe of #500 however this is on a different page, will leave it as a reminder for this page.

@fippo attaching mediastream with null does not resolve this when I tried it last time. I've not taken a closer look but did that work for you?

**Comment by samdutton** [comment] 2015-07-01 06:51
Added a comment to #500.

**Comment by KaptenJansson** [comment] 2015-07-01 06:53
Aha I must have misunderstood, I thought I saw somewhere that we added a call to attachMediastream with a null stream to fix this but it must have been the other way around.

**Comment by fippo** [comment] 2015-07-01 07:00
Am 01.07.2015 um 08:53 schrieb Christoffer Jansson:
> Aha I must have misunderstood, I thought I saw somewhere that we added a call to attachMediastream with a null stream to fix this but it must have been the other way around.

See https://github.com/webrtc/adapter/issues/59 -- for now I think it's 
best to remove the attachMediaStream with null.

**Comment by KaptenJansson** [comment] 2015-07-01 07:10
Aha right now it comes back to me, it was according to the spec as you mentioned. 

I actually have resolved this issue locally while adding output device selection to the source/ demo by removing the attachMediaStream call. I've not yet submitted uploaded that patch though as I found some issues in the output device selection implementation (mind you it's currently under development and behind a flag so very experimental).

Too many things going on at once, must NOT multitask mooore ;)

**Closed** 2015-07-15 12:27 UTC
Labels: bug
