### ISSUE TITLE
Weird behaviour of getUserMedia and safari setting

### ISSUE THREAD

**Issue by DamianBusz** [webrtc/samples#1100] opened 2018-08-24 14:39 UTC
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ x] I have provided steps to reproduce
- [ x] I have provided browser name and version
- [x ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Any latest safari version with ios 11+

## Description
We worked with getUserMedia demo from your examples.
Basically on some iPhones you get asked to allow your camera for streaming and on some iPhones not.
This is weird behavior because on standard safari have camera & audio setting disabled, with this setting disabled it works on most phones(from 5 iphones X it worked on 4) and if it doesn't work you need to flip it on.

## Steps to reproduce
If your lucky, the demo should go on without need for you to activate camera & audio setting in Safari settings, if your unlucky you will need to switch it on.

## Expected results
I actual expect it to work without need of switching the setting.

## Actual results
It works in 80% of times.

**Comment by ErikHellman** [comment] 2018-08-29 06:23
@DamianBusz Can you please provide a proper description of what you do to make it fail and your workaround. I tried looking for the setting you describe but couldn't really find it.

**Comment by ErikHellman** [comment] 2018-09-03 14:45
I will close this issues as I'm not able to reproduce this on the devices I've tried on and haven't received any further updates. Please file a new issue with more details if the problem remains.

**Closed as completed by ErikHellman** 2018-09-03 14:45 UTC
