### ISSUE TITLE
No result on trickle-ice ICE Candidate Gathering

### ISSUE THREAD

**Issue by chris001** [webrtc/samples#833] opened 2016-10-03 00:32 UTC
**Browsers and versions affected**
Firefox 50.0b3

**Description**
Trickle-ICE demo is failing on latest beta of firefox, 50 beta.

**Steps to reproduce**
Go on ICE Candidate Gathering page. 
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
Click button at bottom of screen to get Trickle ICE results.
No results returned even after 30 seconds.

**Expected results**
Results to fill in the table, public IP address, ports, as detected by default public ICE server at google.

**Actual results**
No results returned after a long wait, over 30 seconds.
Web Console shows:

```
488.270: Creating new PeerConnection with config={"iceServers":[{"urls":["stun:stun.l.google.com:19302"]}],"iceTransportPolicy":"all","rtcpMuxPolicy":"negotiate"}, constraints={"optional":[{"googIPv6":true}]}
```

**Comment by fippo** [comment] 2016-10-03 07:42
You don't get host candidates? Does this happen with a fresh profile?

cc @nils-ohlmeier

**Comment by nils-ohlmeier** [comment] 2016-10-03 18:03
@chris001 does this also happen with the current Firefox release 49, or this a new problem with 50 for you?
Could you please open 'about:webrtc' after such a failed attempt and save the log and send to me, post it here or somewhere so I can look at it?

**Comment by chris001** [comment] 2016-10-04 22:48
@nils-ohlmeier 
I have only Firefox 50.0b4 currently installed.  First time user of Trickle-ICE demo page, so I haven't tried it while Firefox 49 was installed (a month ago?).  I could install Firefox 49 if you need a test from there.
Here is the about:webrtc Connection Log, note I pressed the "Gather Candidates" button 3 times, about 10 seconds apart each time:

```
(registry/INFO) insert 'ice' (registry) succeeded: ice
(registry/INFO) insert 'ice.pref' (registry) succeeded: ice.pref
(registry/INFO) insert 'ice.pref.type' (registry) succeeded: ice.pref.type
(registry/INFO) insert 'ice.pref.type.srv_rflx' (UCHAR) succeeded: 0x64
(registry/INFO) insert 'ice.pref.type.peer_rflx' (UCHAR) succeeded: 0x6e
(registry/INFO) insert 'ice.pref.type.host' (UCHAR) succeeded: 0x7e
(registry/INFO) insert 'ice.pref.type.relayed' (UCHAR) succeeded: 0x05
(registry/INFO) insert 'ice.pref.type.srv_rflx_tcp' (UCHAR) succeeded: 0x63
(registry/INFO) insert 'ice.pref.type.peer_rflx_tcp' (UCHAR) succeeded: 0x6d
(registry/INFO) insert 'ice.pref.type.host_tcp' (UCHAR) succeeded: 0x7d
(registry/INFO) insert 'ice.pref.type.relayed_tcp' (UCHAR) succeeded: 0x00
(registry/INFO) insert 'stun' (registry) succeeded: stun
(registry/INFO) insert 'stun.client' (registry) succeeded: stun.client
(registry/INFO) insert 'stun.client.maximum_transmits' (UINT4) succeeded: 7
(registry/INFO) insert 'ice.trickle_grace_period' (UINT4) succeeded: 5000
(registry/INFO) insert 'ice.tcp' (registry) succeeded: ice.tcp
(registry/INFO) insert 'ice.tcp.so_sock_count' (INT4) succeeded: 0
(registry/INFO) insert 'ice.tcp.listen_backlog' (INT4) succeeded: 10
(registry/INFO) insert 'ice.tcp.disable' (char) succeeded: \001
(ice/WARNING) ICE(PC:1475620983960000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)): peer (PC:1475620983960000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/):default) has no stream matching stream 0-1475620983960000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) aLevel=0
(ice/WARNING) ICE(PC:1475621029512000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)): peer (PC:1475621029512000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/):default) has no stream matching stream 0-1475621029512000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) aLevel=0
(ice/WARNING) ICE(PC:1475621067569000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)): peer (PC:1475621067569000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/):default) has no stream matching stream 0-1475621067569000 (id=984 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) aLevel=0
+++++++ END ++++++++
```

**Comment by nils-ohlmeier** [comment] 2016-10-04 22:57
That log is awfully silent/empty.
@chris001 which OS are you on?

**Comment by chris001** [comment] 2016-10-05 09:19
This was Firefox 50.0b4 32 bit, on Windows 10 Pro 64 bit.  Could it possibly be the Avast antivirus webshield interfering with the network traffic.   Update: It's not that, tried disabling the firewall, same, no results.

**Comment by chris001** [comment] 2016-10-10 20:26
Update: Tested on Microsoft Edge, same windows 10 x64 PC, the Trickle-Ice demo is working fine.
1. Which browsers are you using for testing?
2. What are your results on FireFox 50, and Edge 25 ??

**Comment by nils-ohlmeier** [comment] 2016-10-11 19:13
Thanks for the updates @chris001 
The log file I would like to get from you currently can't be taken on our official Windows release builds. So I just wanted to let you know that I'm working on some code in this bug report here https://bugzilla.mozilla.org/show_bug.cgi?id=1309129 which should allow you to create a log file, from which then I can hopefully find out why Firefox on your Windows machine fails to gather host candidates.

**Comment by nils-ohlmeier** [comment] 2016-10-27 18:51
@chris001 if you can still reproduce the problem could you please download this new Firefox build https://archive.mozilla.org/pub/firefox/try-builds/drno@ohlmeier.org-a10f5bb1361ffb82d3d7e318bd0778f053ffacfa/try-win32/firefox-52.0a1.en-US.win32.zip and check if that fixes the issue for you?

**Comment by nils-ohlmeier** [comment] 2016-10-27 18:52
If you want or need different binaries here are other platforms and 64bit binaries etc of the same build https://archive.mozilla.org/pub/firefox/try-builds/drno@ohlmeier.org-a10f5bb1361ffb82d3d7e318bd0778f053ffacfa/

**Comment by chris001** [comment] 2016-10-28 13:19
```
(registry/INFO) insert 'ice' (registry) succeeded: ice
(registry/INFO) insert 'ice.pref' (registry) succeeded: ice.pref
(registry/INFO) insert 'ice.pref.type' (registry) succeeded: ice.pref.type
(registry/INFO) insert 'ice.pref.type.srv_rflx' (UCHAR) succeeded: 0x64
(registry/INFO) insert 'ice.pref.type.peer_rflx' (UCHAR) succeeded: 0x6e
(registry/INFO) insert 'ice.pref.type.host' (UCHAR) succeeded: 0x7e
(registry/INFO) insert 'ice.pref.type.relayed' (UCHAR) succeeded: 0x05
(registry/INFO) insert 'ice.pref.type.srv_rflx_tcp' (UCHAR) succeeded: 0x63
(registry/INFO) insert 'ice.pref.type.peer_rflx_tcp' (UCHAR) succeeded: 0x6d
(registry/INFO) insert 'ice.pref.type.host_tcp' (UCHAR) succeeded: 0x7d
(registry/INFO) insert 'ice.pref.type.relayed_tcp' (UCHAR) succeeded: 0x00
(registry/INFO) insert 'stun' (registry) succeeded: stun
(registry/INFO) insert 'stun.client' (registry) succeeded: stun.client
(registry/INFO) insert 'stun.client.maximum_transmits' (UINT4) succeeded: 7
(registry/INFO) insert 'ice.trickle_grace_period' (UINT4) succeeded: 5000
(registry/INFO) insert 'ice.tcp' (registry) succeeded: ice.tcp
(registry/INFO) insert 'ice.tcp.so_sock_count' (INT4) succeeded: 0
(registry/INFO) insert 'ice.tcp.listen_backlog' (INT4) succeeded: 10
(registry/INFO) insert 'ice.tcp.disable' (char) succeeded: \001
(generic/EMERG) Exit UDP socket connected
(generic/ERR) UDP socket error:Internal error at c:/builds/moz2_slave/try-w32-0000000000000000000000/build/src/dom/network/UDPSocketParent.cpp:123 this=0B51E460
(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.0.139:52439/UDP|stun.l.google.com:19302)): Received response; processing
(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.0.139:52440/UDP|stun.l.google.com:19302)): Received response; processing
(ice/WARNING) ICE(PC:1477660069614000 (id=4294967310 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)): peer (PC:1477660069614000 (id=4294967310 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/):default) has no stream matching stream 0-1477660069614000 (id=4294967310 url=https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) aLevel=0
+++++++ END ++++++++
```

Thanks to you @nils-ohlmeier , Firefox Nightly 52.0a1 (Win32) provides several ICE candidates.
Just wondering, did you improve anything in the Firefox code for it to run ICE differently?

**Comment by KaptenJansson** [comment] 2018-03-08 14:08
Closing due to age.

**Closed as completed by KaptenJansson** 2018-03-08 14:08 UTC
